pipeline:
  build:
    image: 26051992/iisrepo
    commands:
      - yarn
  docker:
    image: plugins/docker
    repo: 26051992/iisrepo
    tags: latest
    secrets: [ DRONE_USERNAME. DRONE_PASSWORD ]
